# Generated by Django 5.2.3 on 2025-07-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemImage',
            new_name='ProductImage',
        ),
    ]
