# Generated by Django 5.2.3 on 2025-07-01 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_itemimage_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='item',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='item',
            new_name='product',
        ),
    ]
